version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_USER=admin       # The admin user
      - POSTGRES_PASSWORD=adminpassword  # Password for admin user
      - POSTGRES_DB=social_media  # Default database
    ports:
      - "5432:5432"  # Expose PostgreSQL port
    volumes:
      - ./init:/docker-entrypoint-initdb.d  # Mount initialization scripts
    networks:
      - social-media-net
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8085:80"  # Access pgAdmin UI on port 8080
    depends_on:
      - db
    networks:
      - social-media-net
    restart: always

volumes:
  postgres_data:

networks:
  social-media-net:
    driver: bridge
